// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package upstreamcommit_test

import (
	"path/filepath"
	"testing"

	"github.com/microsoft/azure-linux-dev-tools/internal/global/testctx"
	"github.com/microsoft/azure-linux-dev-tools/internal/projectconfig"
	"github.com/microsoft/azure-linux-dev-tools/internal/upstreamcommit"
	"github.com/microsoft/azure-linux-dev-tools/internal/utils/fileperms"
	"github.com/microsoft/azure-linux-dev-tools/internal/utils/fileutils"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const testStoreDir = "/project/base/upstream-commits"

func TestStoreSaveAndGet(t *testing.T) {
	ctx := testctx.NewCtx()
	store := upstreamcommit.NewStore(ctx.FS(), testStoreDir)

	require.NoError(t, store.Save("bash", "abcdef1234567"))

	data, err := fileutils.ReadFile(ctx.FS(), filepath.Join(testStoreDir, "bash.toml"))
	require.NoError(t, err)
	assert.Equal(t, `# Generated by azldev component update.
[components]
[components.bash]
[components.bash.spec]
type = 'upstream'
upstream-commit = 'abcdef1234567'
`, string(data))

	commit, exists, err := store.Get("bash")
	require.NoError(t, err)
	assert.True(t, exists)
	assert.Equal(t, "abcdef1234567", commit)

	require.NoError(t, store.Save("bash", "1234567abcdef"))
	commit, exists, err = store.Get("bash")
	require.NoError(t, err)
	assert.True(t, exists)
	assert.Equal(t, "1234567abcdef", commit)
}

func TestStoreGetMissing(t *testing.T) {
	ctx := testctx.NewCtx()
	store := upstreamcommit.NewStore(ctx.FS(), testStoreDir)

	commit, exists, err := store.Get("missing")
	require.NoError(t, err)
	assert.False(t, exists)
	assert.Empty(t, commit)
}

func TestStoreRejectsInvalidComponentName(t *testing.T) {
	ctx := testctx.NewCtx()
	store := upstreamcommit.NewStore(ctx.FS(), testStoreDir)

	_, err := store.Path("../outside")
	require.Error(t, err)
	require.Error(t, store.Save("../outside", "abcdef1"))
}

func TestStoreReportsInvalidTOML(t *testing.T) {
	ctx := testctx.NewCtx()
	store := upstreamcommit.NewStore(ctx.FS(), testStoreDir)
	path := filepath.Join(testStoreDir, "bash.toml")
	require.NoError(t, fileutils.MkdirAll(ctx.FS(), testStoreDir))
	require.NoError(t, fileutils.WriteFile(ctx.FS(), path, []byte("invalid = ["), fileperms.PublicFile))

	_, exists, err := store.Get("bash")
	assert.True(t, exists)
	require.ErrorContains(t, err, "parsing upstream commit TOML")
	require.ErrorContains(t, store.Save("bash", "abcdef1"), "parsing upstream commit TOML")
}

func TestStoreFindAndPruneOrphans(t *testing.T) {
	ctx := testctx.NewCtx()

	store := upstreamcommit.NewStore(ctx.FS(), testStoreDir)
	for _, name := range []string{"kept", "local", "removed"} {
		require.NoError(t, store.Save(name, "abcdef1"))
	}

	components := map[string]projectconfig.ComponentConfig{
		"kept": {
			Spec: projectconfig.SpecSource{SourceType: projectconfig.SpecSourceTypeUpstream},
		},
		"local": {
			Spec: projectconfig.SpecSource{SourceType: projectconfig.SpecSourceTypeLocal},
		},
	}

	orphans, err := store.FindOrphans(components)
	require.NoError(t, err)
	assert.Equal(t, []string{"local", "removed"}, orphans)

	pruned, err := store.PruneOrphans(components)
	require.NoError(t, err)
	assert.Equal(t, 2, pruned)

	_, exists, err := store.Get("kept")
	require.NoError(t, err)
	assert.True(t, exists)
	_, exists, err = store.Get("removed")
	require.NoError(t, err)
	assert.False(t, exists)
}
