// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//go:build scenario

package scenario_tests

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/microsoft/azure-linux-dev-tools/internal/projectconfig"
	"github.com/microsoft/azure-linux-dev-tools/internal/utils/fileperms"
	"github.com/microsoft/azure-linux-dev-tools/scenario/internal/projecttest"
	"github.com/microsoft/azure-linux-dev-tools/scenario/internal/testhelpers"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// minimalDistroTOML provides a minimal distro config for local scenario tests
// that don't use UseTestDefaultConfigs (which requires container mode).
const minimalDistroTOML = `[distros.testdistro]
description = "Test Distro"

[distros.testdistro.versions.'1.0']
release-ver = "1.0"
`

// patchProjectForLocal appends includes and default-distro to the project config
// so it works without UseTestDefaultConfigs. Call after Serialize.
func patchProjectForLocal(t *testing.T, projectDir string) {
	t.Helper()

	configPath := filepath.Join(projectDir, "azldev.toml")
	data, err := os.ReadFile(configPath)
	require.NoError(t, err)

	// Keep an always-present component override and generated-commit placeholder
	// so normal include expansion succeeds even in commits without overrides or
	// generated commit files.
	writeFileInDir(t, projectDir, "component-changes.toml", "")
	writeFileInDir(t, projectDir, "base/upstream-commits/_placeholder.toml", "")

	// Inject includes at the top (before any table headers) and default-distro
	// immediately after the [project] header.
	content := string(data)
	content = `includes = [
    "distro.toml",
    "component-changes.toml",
    "base/upstream-commits/*.toml",
]
` + content

	const projectHeader = "[project]"

	require.True(t, strings.Contains(content, projectHeader),
		"azldev.toml must contain %#q for patchProjectForLocal to work", projectHeader)

	content = strings.Replace(content,
		projectHeader,
		projectHeader+"\ndefault-distro = { name = \"testdistro\", version = \"1.0\" }",
		1,
	)

	require.NoError(t, os.WriteFile(configPath, []byte(content), fileperms.PublicFile))
}

// changedResult mirrors [component.ChangedResult] for JSON deserialization.
type changedResult struct {
	Component     string `json:"component"`
	ChangeType    string `json:"changeType"`
	SourcesChange bool   `json:"sourcesChange"`
}

// gitInDir runs a git command in the specified directory.
func gitInDir(t *testing.T, dir string, args ...string) string {
	t.Helper()

	cmd := exec.CommandContext(t.Context(), "git", args...)
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	require.NoError(t, err, "git %v failed: %s", args, string(out))

	return strings.TrimSpace(string(out))
}

func upstreamCommitConfig(name, commit string) string {
	return fmt.Sprintf(
		"# This file was generated by 'azldev component refresh-upstream-commit'\n"+
			"# Do not edit this file, changes will be lost\n"+
			"# For more details see 'azldev component refresh-upstream-commit --help'\n"+
			"[components.%s.spec]\nupstream-commit = %q\n",
		name,
		commit,
	)
}

func projectComponentConfig(name string) string {
	return fmt.Sprintf(
		`[components.%s.spec]
type = "upstream"
upstream-distro = { name = "testdistro", version = "1.0" }
upstream-name = %q
`, name, name)
}

func upstreamComponent(name string) *projectconfig.ComponentConfig {
	return &projectconfig.ComponentConfig{
		Name: name,
		Spec: projectconfig.SpecSource{
			SourceType: projectconfig.SpecSourceTypeUpstream,
			UpstreamDistro: projectconfig.DistroReference{
				Name:    "testdistro",
				Version: "1.0",
			},
			UpstreamName: name,
		},
	}
}

// writeFileInDir creates a file at relPath under dir with the given content.
func writeFileInDir(t *testing.T, dir, relPath, content string) {
	t.Helper()

	absPath := filepath.Join(dir, relPath)
	require.NoError(t, os.MkdirAll(filepath.Dir(absPath), fileperms.PublicDir))
	require.NoError(t, os.WriteFile(absPath, []byte(content), fileperms.PublicFile))
}

// TestComponentChanged_E2E exercises the full `azldev component changed` command
// with a real git repository, verifying JSON output for multi-component change
// detection.
//
// Flow:
//  1. Create a project with two upstream components (curl, bash) and a minimal
//     distro config patched in for local (non-container) execution.
//  2. Commit initial upstream commit TOMLs for both components with distinct commits.
//  3. In a second commit, update curl's generated TOML and change bash's
//     ordinary build configuration through another included TOML.
//  4. Run `azldev component changed --from <commit1> -a --include-unchanged`
//     to compare the two commits with JSON output.
//  5. Assert both are "changed", proving generated and hand-written component
//     config are compared through the same normal project-loading path.
func TestComponentChanged_E2E(t *testing.T) {
	t.Parallel()

	if testing.Short() {
		t.Skip("skipping long test")
	}

	azldevBin, err := testhelpers.FindTestBinary()
	require.NoError(t, err)

	// Create a project with two local components.
	projectDir := t.TempDir()

	spec1 := projecttest.NewSpec(
		projecttest.WithName("curl"),
		projecttest.WithVersion("8.0.0"),
		projecttest.WithRelease("1%{?dist}"),
		projecttest.WithBuildArch(projecttest.NoArch),
	)

	spec2 := projecttest.NewSpec(
		projecttest.WithName("bash"),
		projecttest.WithVersion("5.2.0"),
		projecttest.WithRelease("1%{?dist}"),
		projecttest.WithBuildArch(projecttest.NoArch),
	)

	project := projecttest.NewDynamicTestProject(
		projecttest.AddSpec(spec1),
		projecttest.AddSpec(spec2),
		projecttest.AddComponent(upstreamComponent("curl")),
		projecttest.AddComponent(upstreamComponent("bash")),
		projecttest.AddFile("distro.toml", minimalDistroTOML),
	)

	project.Serialize(t, projectDir)
	patchProjectForLocal(t, projectDir)

	// Step 2: Initialize git repo. Create upstream commit TOMLs for both components
	// with version 1 upstream commits, then commit everything as the baseline.
	gitInDir(t, projectDir, "init")
	gitInDir(t, projectDir, "config", "user.email", "test@test.com")
	gitInDir(t, projectDir, "config", "user.name", "Test")

	commitV1Curl := upstreamCommitConfig("curl", "1111111")
	commitV1Bash := upstreamCommitConfig("bash", "bbbbbbb")

	writeFileInDir(t, projectDir, "base/upstream-commits/curl.toml", commitV1Curl)
	writeFileInDir(t, projectDir, "base/upstream-commits/bash.toml", commitV1Bash)

	gitInDir(t, projectDir, "add", ".")
	gitInDir(t, projectDir, "-c", "commit.gpgsign=false", "commit", "-m", "initial")

	fromRef := gitInDir(t, projectDir, "rev-parse", "HEAD")

	// Second commit: change curl's generated pin and an unrelated ordinary
	// component field for bash.
	commitV2Curl := upstreamCommitConfig("curl", "2222222")
	writeFileInDir(t, projectDir, "base/upstream-commits/curl.toml", commitV2Curl)
	writeFileInDir(t, projectDir, "component-changes.toml", `[components.bash.build]
defines = { feature = "enabled" }
`)

	gitInDir(t, projectDir, "add",
		"base/upstream-commits/curl.toml", "component-changes.toml")
	gitInDir(t, projectDir, "-c", "commit.gpgsign=false", "commit", "-m", "update components")

	// Run: all components, include unchanged.
	cmd := exec.CommandContext(t.Context(),
		azldevBin, "-C", projectDir, "--no-default-config", "component", "changed",
		"--from", fromRef, "-a", "--include-unchanged", "-q", "-O", "json",
	)
	out, err := cmd.CombinedOutput()
	require.NoError(t, err, "azldev failed: %s", string(out))

	var results []changedResult
	require.NoError(t, json.Unmarshal(out, &results), "failed to parse JSON: %s", string(out))

	// Build a map for easy lookup.
	resultMap := make(map[string]changedResult)
	for _, result := range results {
		resultMap[result.Component] = result
	}

	// curl should be changed.
	curlResult, ok := resultMap["curl"]
	require.True(t, ok, "curl should be in results")
	assert.Equal(t, "changed", curlResult.ChangeType, "curl upstream commit changed")

	// bash should also change because its build-relevant configuration changed.
	bashResult, ok := resultMap["bash"]
	require.True(t, ok, "bash should be in results (--all-components)")
	assert.Equal(t, "changed", bashResult.ChangeType, "bash build configuration changed")
}

// TestComponentChanged_SameRef verifies that comparing a ref to itself produces
// no changes.
func TestComponentChanged_SameRef(t *testing.T) {
	t.Parallel()

	if testing.Short() {
		t.Skip("skipping long test")
	}

	azldevBin, err := testhelpers.FindTestBinary()
	require.NoError(t, err)

	projectDir := t.TempDir()

	spec := projecttest.NewSpec(
		projecttest.WithName("curl"),
		projecttest.WithVersion("1.0.0"),
		projecttest.WithRelease("1%{?dist}"),
		projecttest.WithBuildArch(projecttest.NoArch),
	)

	project := projecttest.NewDynamicTestProject(
		projecttest.AddSpec(spec),
		projecttest.AddComponent(upstreamComponent("curl")),
		projecttest.AddFile("distro.toml", minimalDistroTOML),
	)

	project.Serialize(t, projectDir)
	patchProjectForLocal(t, projectDir)

	gitInDir(t, projectDir, "init")
	gitInDir(t, projectDir, "config", "user.email", "test@test.com")
	gitInDir(t, projectDir, "config", "user.name", "Test")

	commitConfig := upstreamCommitConfig("curl", "1111111")
	writeFileInDir(t, projectDir, "base/upstream-commits/curl.toml", commitConfig)

	gitInDir(t, projectDir, "add", ".")
	gitInDir(t, projectDir, "-c", "commit.gpgsign=false", "commit", "-m", "initial")

	ref := gitInDir(t, projectDir, "rev-parse", "HEAD")

	// Compare ref to itself — include unchanged so we get results.
	cmd := exec.CommandContext(t.Context(),
		azldevBin, "-C", projectDir, "--no-default-config", "component", "changed",
		"--from", ref, "--to", ref, "-a", "--include-unchanged", "-q", "-O", "json",
	)
	out, err := cmd.CombinedOutput()
	require.NoError(t, err, "azldev failed: %s", string(out))

	var results []changedResult
	require.NoError(t, json.Unmarshal(out, &results), "failed to parse JSON: %s", string(out))

	require.NotEmpty(t, results, "same-ref comparison should return at least one component")

	for _, result := range results {
		assert.Equal(t, "unchanged", result.ChangeType, "no changes expected for same-ref comparison: %s", result.Component)
	}
}

// runChanged runs `azldev component changed` with the given args and returns
// parsed JSON results. Fails the test on any error.
func runChanged(t *testing.T, azldevBin, projectDir string, extraArgs ...string) []changedResult {
	t.Helper()

	args := []string{"-C", projectDir, "--no-default-config", "component", "changed"}
	args = append(args, extraArgs...)
	args = append(args, "-q", "-O", "json")

	cmd := exec.CommandContext(t.Context(), azldevBin, args...)
	out, err := cmd.CombinedOutput()
	require.NoError(t, err, "azldev failed: %s", string(out))

	var results []changedResult
	require.NoError(t, json.Unmarshal(out, &results), "failed to parse JSON: %s", string(out))

	return results
}

// resultMap converts a slice of changedResult into a map keyed by component name.
func resultMap(results []changedResult) map[string]changedResult {
	m := make(map[string]changedResult, len(results))
	for _, r := range results {
		m[r.Component] = r
	}

	return m
}

// setupProjectWithGit creates a project with the given specs and components,
// initializes a git repo, and returns (azldevBin, projectDir). The project has
// a minimal distro config patched in for local execution.
func setupProjectWithGit(
	t *testing.T,
	specs []*projecttest.TestSpec,
	components []*projectconfig.ComponentConfig,
	extraFiles map[string]string,
) (string, string) {
	t.Helper()

	azldevBin, err := testhelpers.FindTestBinary()
	require.NoError(t, err)

	projectDir := t.TempDir()

	opts := []projecttest.DynamicTestProjectOption{
		projecttest.AddFile("distro.toml", minimalDistroTOML),
	}

	for _, spec := range specs {
		opts = append(opts, projecttest.AddSpec(spec))
	}

	for _, comp := range components {
		opts = append(opts, projecttest.AddComponent(comp))
	}

	// Sort keys for deterministic option ordering.
	extraKeys := make([]string, 0, len(extraFiles))
	for path := range extraFiles {
		extraKeys = append(extraKeys, path)
	}

	sort.Strings(extraKeys)

	for _, path := range extraKeys {
		opts = append(opts, projecttest.AddFile(path, extraFiles[path]))
	}

	project := projecttest.NewDynamicTestProject(opts...)
	project.Serialize(t, projectDir)
	patchProjectForLocal(t, projectDir)

	gitInDir(t, projectDir, "init")
	gitInDir(t, projectDir, "config", "user.email", "test@test.com")
	gitInDir(t, projectDir, "config", "user.name", "Test")

	return azldevBin, projectDir
}

// TestComponentChanged_SourcesChange verifies that the sources change column
// correctly reflects rendered sources file changes.
//
// Flow:
//  1. Create a project with one component (curl) and a rendered-specs-dir.
//  2. Commit initial upstream commit TOML + sources file.
//  3. In a second commit, update the upstream commit AND the sources file.
//  4. Assert changeType="changed" and sourcesChange="true".
//  5. In a third commit, update only the commit TOML (not sources).
//  6. Compare commit 2→3: assert changeType="changed", sourcesChange="false"
//     (rebuild needed but no tarball re-upload).
func TestComponentChanged_SourcesChange(t *testing.T) {
	t.Parallel()

	if testing.Short() {
		t.Skip("skipping long test")
	}

	azldevBin, projectDir := setupProjectWithGit(t,
		[]*projecttest.TestSpec{
			projecttest.NewSpec(
				projecttest.WithName("curl"),
				projecttest.WithVersion("8.0.0"),
				projecttest.WithRelease("1%{?dist}"),
				projecttest.WithBuildArch(projecttest.NoArch),
			),
		},
		[]*projectconfig.ComponentConfig{upstreamComponent("curl")},
		nil,
	)

	// Commit 1: initial commit TOML + rendered sources.
	writeFileInDir(t, projectDir, "base/upstream-commits/curl.toml",
		upstreamCommitConfig("curl", "1111111"))
	writeFileInDir(t, projectDir, "specs/c/curl/sources",
		"SHA512 (curl-8.0.tar.gz) = aaa111")
	gitInDir(t, projectDir, "add", ".")
	gitInDir(t, projectDir, "-c", "commit.gpgsign=false", "commit", "-m", "initial")
	ref1 := gitInDir(t, projectDir, "rev-parse", "HEAD")

	// Commit 2: change upstream commit AND sources (new tarball).
	writeFileInDir(t, projectDir, "base/upstream-commits/curl.toml",
		upstreamCommitConfig("curl", "2222222"))
	writeFileInDir(t, projectDir, "specs/c/curl/sources",
		"SHA512 (curl-8.1.tar.gz) = bbb222")
	gitInDir(t, projectDir, "add", ".")
	gitInDir(t, projectDir, "-c", "commit.gpgsign=false", "commit", "-m", "update sources")
	ref2 := gitInDir(t, projectDir, "rev-parse", "HEAD")

	// Commit 3: change upstream commit only (same tarball).
	writeFileInDir(t, projectDir, "base/upstream-commits/curl.toml",
		upstreamCommitConfig("curl", "3333333"))
	gitInDir(t, projectDir, "add", ".")
	gitInDir(t, projectDir, "-c", "commit.gpgsign=false", "commit", "-m", "config change")

	// ref1 → ref2: upstream commit AND sources changed.
	results := runChanged(t, azldevBin, projectDir, "--from", ref1, "--to", ref2, "-a")
	rm := resultMap(results)
	require.Contains(t, rm, "curl")
	assert.Equal(t, "changed", rm["curl"].ChangeType)
	assert.True(t, rm["curl"].SourcesChange, "sources file changed between refs")

	// ref2 → HEAD: upstream commit changed, sources unchanged.
	results = runChanged(t, azldevBin, projectDir, "--from", ref2, "-a")
	rm = resultMap(results)
	require.Contains(t, rm, "curl")
	assert.Equal(t, "changed", rm["curl"].ChangeType)
	assert.False(t, rm["curl"].SourcesChange, "sources file identical — rebuild without re-upload")
}

// TestComponentChanged_InvertedRefs verifies that swapping --from and --to
// produces correct results in the reverse direction.
//
// Flow:
//  1. Create a project with one component, commit two versions of its upstream commit TOML.
//  2. Compare forward (old→new): changeType="changed".
//  3. Compare backward (new→old): also changeType="changed" (upstream commit
//     still differs, just in the other direction).
func TestComponentChanged_InvertedRefs(t *testing.T) {
	t.Parallel()

	if testing.Short() {
		t.Skip("skipping long test")
	}

	azldevBin, projectDir := setupProjectWithGit(t,
		[]*projecttest.TestSpec{
			projecttest.NewSpec(
				projecttest.WithName("curl"),
				projecttest.WithVersion("1.0.0"),
				projecttest.WithRelease("1%{?dist}"),
				projecttest.WithBuildArch(projecttest.NoArch),
			),
		},
		[]*projectconfig.ComponentConfig{upstreamComponent("curl")},
		nil,
	)

	// Commit 1: v1 commit TOML.
	writeFileInDir(t, projectDir, "base/upstream-commits/curl.toml",
		upstreamCommitConfig("curl", "1111111"))
	gitInDir(t, projectDir, "add", ".")
	gitInDir(t, projectDir, "-c", "commit.gpgsign=false", "commit", "-m", "v1")
	oldRef := gitInDir(t, projectDir, "rev-parse", "HEAD")

	// Commit 2: v2 commit TOML.
	writeFileInDir(t, projectDir, "base/upstream-commits/curl.toml",
		upstreamCommitConfig("curl", "2222222"))
	gitInDir(t, projectDir, "add", ".")
	gitInDir(t, projectDir, "-c", "commit.gpgsign=false", "commit", "-m", "v2")
	newRef := gitInDir(t, projectDir, "rev-parse", "HEAD")

	// Forward: old → new.
	forward := runChanged(t, azldevBin, projectDir, "--from", oldRef, "--to", newRef, "-a")
	rm := resultMap(forward)
	require.Contains(t, rm, "curl")
	assert.Equal(t, "changed", rm["curl"].ChangeType, "forward: upstream commit differs")

	// Backward: new → old (inverted).
	backward := runChanged(t, azldevBin, projectDir, "--from", newRef, "--to", oldRef, "-a")
	rm = resultMap(backward)
	require.Contains(t, rm, "curl")
	assert.Equal(t, "changed", rm["curl"].ChangeType, "backward: upstream commit still differs")
}

// TestComponentChanged_NewComponent verifies that a component added to normal
// project TOML between the two refs is reported as "added".
//
// Flow:
//  1. Commit a project without newpkg.
//  2. Add newpkg to an included component config.
//  3. Compare: newpkg should be "added".
func TestComponentChanged_NewComponent(t *testing.T) {
	t.Parallel()

	if testing.Short() {
		t.Skip("skipping long test")
	}

	azldevBin, projectDir := setupProjectWithGit(t,
		[]*projecttest.TestSpec{
			projecttest.NewSpec(
				projecttest.WithName("curl"),
				projecttest.WithVersion("1.0.0"),
				projecttest.WithRelease("1%{?dist}"),
				projecttest.WithBuildArch(projecttest.NoArch),
			),
		},
		[]*projectconfig.ComponentConfig{{
			Name: "curl",
			Spec: projectconfig.SpecSource{
				SourceType: projectconfig.SpecSourceTypeLocal,
				Path:       filepath.Join("specs", "curl", "curl.spec"),
			},
		}},
		nil,
	)

	gitInDir(t, projectDir, "add", ".")
	gitInDir(t, projectDir, "-c", "commit.gpgsign=false", "commit", "-m", "empty")
	fromRef := gitInDir(t, projectDir, "rev-parse", "HEAD")

	// Commit 2: add a complete component definition through a normal include.
	writeFileInDir(t, projectDir, "component-changes.toml",
		projectComponentConfig("newpkg"))
	gitInDir(t, projectDir, "add", ".")
	gitInDir(t, projectDir, "-c", "commit.gpgsign=false", "commit", "-m", "add newpkg")

	results := runChanged(t, azldevBin, projectDir, "--from", fromRef, "-a")
	rm := resultMap(results)
	require.Contains(t, rm, "newpkg")
	assert.Equal(t, "added", rm["newpkg"].ChangeType, "new component should be reported as added")
}

// TestComponentChanged_DeletedComponent verifies that a component removed from
// normal project TOML is reported as "deleted".
//
// Flow:
//  1. Commit a normal component definition for oldpkg.
//  2. Remove oldpkg's definition in a second commit.
//  3. Compare with -a: oldpkg should appear as "deleted".
func TestComponentChanged_DeletedComponent(t *testing.T) {
	t.Parallel()

	if testing.Short() {
		t.Skip("skipping long test")
	}

	azldevBin, projectDir := setupProjectWithGit(t,
		[]*projecttest.TestSpec{
			projecttest.NewSpec(
				projecttest.WithName("curl"),
				projecttest.WithVersion("1.0.0"),
				projecttest.WithRelease("1%{?dist}"),
				projecttest.WithBuildArch(projecttest.NoArch),
			),
		},
		[]*projectconfig.ComponentConfig{{
			Name: "curl",
			Spec: projectconfig.SpecSource{
				SourceType: projectconfig.SpecSourceTypeLocal,
				Path:       filepath.Join("specs", "curl", "curl.spec"),
			},
		}},
		nil,
	)

	// Commit 1: oldpkg is a real component loaded through a normal include.
	writeFileInDir(t, projectDir, "component-changes.toml",
		projectComponentConfig("oldpkg"))
	gitInDir(t, projectDir, "add", ".")
	gitInDir(t, projectDir, "-c", "commit.gpgsign=false", "commit", "-m", "initial")
	fromRef := gitInDir(t, projectDir, "rev-parse", "HEAD")

	// Commit 2: remove oldpkg's component definition.
	writeFileInDir(t, projectDir, "component-changes.toml", "")
	gitInDir(t, projectDir, "add", "component-changes.toml")
	gitInDir(t, projectDir, "-c", "commit.gpgsign=false", "commit", "-m", "remove oldpkg")

	results := runChanged(t, azldevBin, projectDir, "--from", fromRef, "-a")
	rm := resultMap(results)

	require.Contains(t, rm, "oldpkg", "deleted component should appear in results")
	assert.Equal(t, "deleted", rm["oldpkg"].ChangeType, "removed component definition")
}

// TestComponentChanged_JSONContract validates the JSON output schema is stable
// for CI consumers. Any field rename, type change, or value-set change will
// break this test — that's intentional.
//
// The test exercises all four changeType values (added, changed, unchanged,
// deleted) and both sourcesChange values (true, false) in a single run,
// then validates the raw JSON structure without the changedResult struct
// to catch accidental field renames.
func TestComponentChanged_JSONContract(t *testing.T) {
	t.Parallel()

	if testing.Short() {
		t.Skip("skipping long test")
	}

	azldevBin, projectDir := setupProjectWithGit(t,
		[]*projecttest.TestSpec{
			projecttest.NewSpec(
				projecttest.WithName("curl"),
				projecttest.WithVersion("1.0.0"),
				projecttest.WithRelease("1%{?dist}"),
				projecttest.WithBuildArch(projecttest.NoArch),
			),
			projecttest.NewSpec(
				projecttest.WithName("bash"),
				projecttest.WithVersion("1.0.0"),
				projecttest.WithRelease("1%{?dist}"),
				projecttest.WithBuildArch(projecttest.NoArch),
			),
		},
		[]*projectconfig.ComponentConfig{
			upstreamComponent("curl"),
			upstreamComponent("bash"),
		},
		nil,
	)

	// Commit 1: curl has commit TOML + sources, bash has a commit TOML,
	// and oldpkg is defined in normal project config.
	writeFileInDir(t, projectDir, "base/upstream-commits/curl.toml",
		upstreamCommitConfig("curl", "1111111"))
	writeFileInDir(t, projectDir, "base/upstream-commits/bash.toml",
		upstreamCommitConfig("bash", "bbbbbbb"))
	writeFileInDir(t, projectDir, "component-changes.toml",
		projectComponentConfig("oldpkg"))
	writeFileInDir(t, projectDir, "specs/c/curl/sources",
		"SHA512 (curl-1.0.tar.gz) = aaa")
	gitInDir(t, projectDir, "add", ".")
	gitInDir(t, projectDir, "-c", "commit.gpgsign=false", "commit", "-m", "initial")
	fromRef := gitInDir(t, projectDir, "rev-parse", "HEAD")

	// Commit 2: curl upstream commit + sources changed, bash unchanged,
	// and oldpkg's component definition is removed.
	writeFileInDir(t, projectDir, "base/upstream-commits/curl.toml",
		upstreamCommitConfig("curl", "2222222"))
	writeFileInDir(t, projectDir, "specs/c/curl/sources",
		"SHA512 (curl-2.0.tar.gz) = bbb")
	writeFileInDir(t, projectDir, "component-changes.toml", "")
	gitInDir(t, projectDir, "add", ".")
	gitInDir(t, projectDir, "-c", "commit.gpgsign=false", "commit", "-m", "update")

	// Run with --include-unchanged to get all four states.
	cmd := exec.CommandContext(t.Context(),
		azldevBin, "-C", projectDir, "--no-default-config", "component", "changed",
		"--from", fromRef, "-a", "--include-unchanged", "-q", "-O", "json",
	)
	rawOutput, err := cmd.CombinedOutput()
	require.NoError(t, err, "azldev failed: %s", string(rawOutput))

	// Parse as raw JSON to validate field names without relying on the Go struct.
	var rawResults []map[string]interface{}
	require.NoError(t, json.Unmarshal(rawOutput, &rawResults),
		"output must be a JSON array of objects: %s", string(rawOutput))

	// Validate every result has exactly the expected fields.
	expectedFields := []string{"component", "changeType", "sourcesChange"}

	for idx, row := range rawResults {
		for _, field := range expectedFields {
			_, ok := row[field]
			require.True(t, ok, "row %d missing required field %#q: %v", idx, field, row)
		}

		assert.Len(t, row, len(expectedFields),
			"row %d has unexpected extra fields: %v", idx, row)
	}

	// Validate the value sets via the typed results.
	results := runChanged(t, azldevBin, projectDir,
		"--from", fromRef, "-a", "--include-unchanged")
	rm := resultMap(results)

	// Expected states:
	//   curl:   changed  + sourcesChange=true  (both upstream commit and sources differ)
	//   bash:   unchanged + sourcesChange=false (identical at both refs)
	//   oldpkg: deleted  + sourcesChange=false  (component definition removed)
	validChangeTypes := map[string]bool{
		"added": true, "changed": true, "unchanged": true, "deleted": true,
	}

	for _, r := range results {
		assert.True(t, validChangeTypes[r.ChangeType],
			"component %#q: changeType %#q not in valid set", r.Component, r.ChangeType)
	}

	// Pin specific expected values.
	require.Contains(t, rm, "curl")
	assert.Equal(t, "changed", rm["curl"].ChangeType)
	assert.True(t, rm["curl"].SourcesChange)

	require.Contains(t, rm, "bash")
	assert.Equal(t, "unchanged", rm["bash"].ChangeType)
	assert.False(t, rm["bash"].SourcesChange)

	require.Contains(t, rm, "oldpkg")
	assert.Equal(t, "deleted", rm["oldpkg"].ChangeType)
}

// TestComponentChanged_SourcesOnlyChange verifies that rendered sources changes
// are reported independently from upstream commit changes.
func TestComponentChanged_SourcesOnlyChange(t *testing.T) {
	t.Parallel()

	if testing.Short() {
		t.Skip("skipping long test")
	}

	azldevBin, projectDir := setupProjectWithGit(t,
		[]*projecttest.TestSpec{
			projecttest.NewSpec(
				projecttest.WithName("curl"),
				projecttest.WithVersion("8.0.0"),
				projecttest.WithRelease("1%{?dist}"),
				projecttest.WithBuildArch(projecttest.NoArch),
			),
		},
		[]*projectconfig.ComponentConfig{upstreamComponent("curl")},
		nil,
	)

	// Commit 1: commit TOML + matching rendered sources.
	writeFileInDir(t, projectDir, "base/upstream-commits/curl.toml",
		upstreamCommitConfig("curl", "1111111"))
	writeFileInDir(t, projectDir, "specs/c/curl/sources",
		"SHA512 (curl-8.0.tar.gz) = aaa111")
	gitInDir(t, projectDir, "add", ".")
	gitInDir(t, projectDir, "-c", "commit.gpgsign=false", "commit", "-m", "initial")
	fromRef := gitInDir(t, projectDir, "rev-parse", "HEAD")

	// Commit 2: edit only the rendered sources file.
	writeFileInDir(t, projectDir, "specs/c/curl/sources",
		"SHA512 (evil-payload.tar.gz) = deadbeef")
	gitInDir(t, projectDir, "add", ".")
	gitInDir(t, projectDir, "-c", "commit.gpgsign=false", "commit", "-m", "tamper")

	results := runChanged(t, azldevBin, projectDir, "--from", fromRef, "-a")
	rm := resultMap(results)

	require.Contains(t, rm, "curl")
	assert.Equal(t, "unchanged", rm["curl"].ChangeType)
	assert.True(t, rm["curl"].SourcesChange)
}
